services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
networks:
  fastapi_network:
    driver: bridge
volumes:
  postgres_data:
